export const TYPES = {
    ADD_ONE_TO_CART: "ADD_ONE_TO_CART",
    REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
    REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
    CLEAR_CART: "CLEAR_CART"
};